linters:
  # all default linters enabled
  enable:
    - gofmt
    - goimports
    - prealloc

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
  