log_level: debug

variables:
  pods:
    resource: pods

  target: podsvt

  resources:
  - name: deployments
    group: apps
    version: v1
    resource: deployments
    namespaces: [validation-test]

  - name: podsvt
    group: ""
    version: v1
    resource: pods
    namespaces: [validation-test]

  full_resource:
  - name: services
    resource-rule:
      group:
      version: v1
      resource: services
      namespaces: [validation-test]

secrets:
  target: podsvt