name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/lula-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
      with:
        name: debug-log
        path: /tmp/lula-*.logd