name: PR Title Check

on:
  pull_request:
    branches: [main]
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, synchronize, edit]

permissions:
  contents: read
  pull-requests: read

jobs:
  title_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: commitlint

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4


      - name: Install commitlint
        run: npm ci --only=dev

      - name: Lint PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint 
