name: GoReleaser Check

on:
  push:
    paths:
      - '.goreleaser.yaml'
  pull_request:
    paths:
      - '.goreleaser.yaml'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          install-only: true

      - name: Run GoReleaser Check
        run: goreleaser check
