name: GoReleaser Check

on:
  push:
    paths:
      - '.goreleaser.yaml'
  pull_request:
    paths:
      - '.goreleaser.yaml'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@f7623f3e7168fa800ac616fe8d03643abbc6edda
        with:
          install-only: true

      - name: Run GoReleaser Check
        run: goreleaser check
