name: E2E Testing

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Setup golang
      uses: ./.github/actions/golang

    - name: Display Go version
      run: go version
      
    - name: e2e Tests
      run: | 
        make test