name: E2E Testing

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    - name: Setup golang
      uses: ./.github/actions/golang

    - name: Display Go version
      run: go version
      
    - name: e2e Tests
      run: | 
        make test